### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by MenatWorx** [filipelinhares/timenow-sublime#1]
Doesn't work for me.
Sublime Text Build 3126 Windows 8.1
Nothing works.

**Comment by filipelinhares** [comment]
Hey @MenatWorx, thanks for your report.

- What Python version are you running?

**Comment by MenatWorx** [comment]
Python 3.6.1

 

 

Sent: Monday, June 19, 2017 at 9:36 AM

**Comment by filipelinhares** [comment]
I tried on Windows and it's working. Are you running v1.0.0? Before it the plugin was not working.

**Comment by MenatWorx** [comment]
Are you running v1.0.0?

 


Yes, I usually do not run pre-version 1.

 

 

Sent: Tuesday, June 20, 2017 at 6:03 PM

**Comment by filipelinhares** [comment]
Could you open the console (View -> Show console) and send the error message?

**Comment by MenatWorx** [comment]
\Sublime Text 3\Installed Packages\Timenow.sublime-package", line 25, in run
TypeError: must be str, not None

 
 
 

Sent: Wednesday, June 21, 2017 at 10:21 AM

**Comment by filipelinhares** [comment]
Finally I found a way to replicate the bug. I'll push a new release with the fix as soon as possible.
Thanks @MenatWorx

**Comment by MenatWorx** [comment]
Thanks.
 

Sent: Monday, June 26, 2017 at 1:58 AM

**Comment by MenatWorx** [comment]
Yes, it works now. Congratulations!  I had mostly given up about it.

 

 
 

Sent: Thursday, July 13, 2017 at 11:12 AM
