### ISSUE TITLE
still doesn't work and the documentation is both wrong and unfinished!

### ISSUE THREAD

**Issue by hsmyers** [filipelinhares/timenow-sublime#2]

**Comment by filipelinhares** [comment]
Hi @hsmyers, thanks for your feedback.
I've [updated](https://github.com/filipelinhares/timenow-sublime/releases/tag/1.1.0) the plugin, can you check if is it working now?

Thanks!

**Comment by hsmyers** [comment]
Thanks,  Flipe,

Will give it a go!!
