### ISSUE TITLE
STILL does not work—and no documentation

### ISSUE THREAD

**Issue by hsmyers** [filipelinhares/timenow-sublime#3]
You close issue without finding out if the issue is fixed. It is not. The plugin does NOTHING.

**Comment by filipelinhares** [comment]
Sorry, I expect the bug was the same #1. 

Could you send more info about the bug?
- Python Version
- Sublime Version
- Open the console (View -> Show console) and send the error message

What you mean with "No documentation"?

**Comment by hsmyers** [comment]
Python 2.7.13 (default, Jan 17 2017, 13:56:44)  [GCC 6.3.0 64 bit (AMD64)]
on win32
Stable Channel, Build 3126

No errors, just wrong action:

17:07:2017-08:38:58 from insert stamp
2017-07-17:20 from insert date
2017-07-17:03 from insert time
2017-07-17:23 from insert datetime

this is current Timenow.sublime-settings-user

/* Mre about those patterns -
http://devdocs.io/python~3.6/library/time#time.strftime
 *
 * date - 2013-10-02
 * time - 10:24:01
 * datetime - 2013-10-02 10:24
 * stamp - 131002102355
 * char *Date = "7/13/2017 12:00:37 PM";
**/

{
"date_format": "%Y-%m-%d:%S",
"time_format": "%H:%M:%S",
"datetime_format": "%a %b %d %H:%M:%S %Y",
"stamp_format": "%d:%m:%Y-%H:%M:%S"
}

I do not think your short readme.md provides complete documentation. Look
at other examples and compare. You seem to have fallen into the trap of
thinking the user knows what you do. While possible, it is best to assume
that the user knows nothing rather than everything.

**Comment by Sixdd6** [comment]
I've just tried this package and when I click any option to insert it doesn't insert anything. The error I am getting is this:

TypeError: must be str, not None

This is the same error for all four options.
